#!/usr/bin/env bash

# verify-init — Verify if current directory is a depot repository

verboseLib="/usr/lib/depot/verbose"

[[ ! -f .depot/init ]] && $verboseLib error "Not a depot repository (missing .depot/init)."

if [[ ! -f $HOME/.depot/settings.conf || ! -f .depot/settings.conf ]] ; then
  $verboseLib warning "Configuration files not found. Using default settings."
fi
