#!/usr/bin/env bash

# verify-init — Verify if current directory is a depot repository

verboseLib="/usr/lib/depot/verbose"

[[ ! -f .depot/init ]] && $verboseLib error "Not a depot repository (missing .depot/init)."

[[ -f $HOME/.depot/settings.conf ]] && source .depot/settings.conf
[[ -f .depot/settings.conf ]] && source .depot/config

[[ ! -f $HOME/.depot/settings.conf && ! -f .depot/settings.conf ]] &&
$verboseLib error "No configuration found (missing .depot/config or \$HOME/.depot/config)."

return 0
