# This is a build configuration file that specifies some
# parameters for the build process using dpkg-buildpackage.

signing:
  # Whether to sign the package
  sign: true

  # Key ID to use: The name or fingerprint of the key
  key_id: MLS Tidbits Packages

build:
  # The architecture to build for
  architecture: amd64

  # What to build, the options are:
  # - source: Only the source package
  # - binary: Only the binary package
  # - all:    All packages (source, binary, and all architecture)
  # Default is 'binary'
  type: binary
