key:
  enable: true
  name: dpkg-archive

release:
  origin:
  label:
  suite:
  codename:
  architectures: amd64
  components: main
  description: Dpkg Archive is a tool for managing Debian package archives.

maintainer:
  name: MLS Tidbits
  email: contact@mlstidbits.com
