#!/usr/bin/env bash

# `depot` Creates, maintains and updates a Debian package repository.

# Update the package and Release/InRelease files keeping the repository
# structure intact.

# Uncomment the following line to enable debugging
# set -xou pipefail

function app-info {

    case "$1" in
        info       ) echo -e "$appTitle - [$1] $2" ;;
        warning    ) echo -e "$appTitle - [$1] $2" ;;
        error      ) echo -e "$appTitle - [$1] $2" ; exit 1 ;;
        *          ) echo -e "$appTitle - [unknown] $2" ;;
    esac

}

appTitle="depot"

# Change mapfile to /usr/share/doc/depot for production releases
appVersion="$(cat doc/version 2>/dev/null || echo "unknown")"

copyright="$(cat <<- EOL
Copyright:
    2025 MLS Tidbits <contact@mlstidbits.com>
    2025 Michael Schaecher <michaelschaecher@mlstidbits.com>
License:
    GPLv3+ as published by the Free Software Foundation all rights reserved.
EOL
)"

appInfo="$(cat <<- EOL
$appTitle - $appVersion - A simple Debian package repository manager.
EOL
)"

appHelp="$(cat <<- EOL
$appInfo
Usage: $0 [options] <command> [<args>]

Commands:
    init                    Initialize a new repository
    add <package>...        Add one or more .deb packages to the repository
    remove <package>        Remove a package from the repository
    update                  Update the Release and InRelease files
    sign                    Sign the Release file with GPG
    help                    Show this help message
    version                 Show version information
    help                    Show this help message
    version                 Show version information
Options:
    -h, --help              Show this help message for \`help\`, \`init\`, \`add\`,
                            \`remove\`, \`update\` and \`sign\` commands

$copyright
EOL
)"

[[ $# -eq 0 ]] && { echo "$appHelp" ; exit 0 ; }

case "$1" in
    init                    ) shift ; /usr/lib/depot/init "$@"          ;;
    add                     ) shift ; /usr/lib/depot/add "$@"           ;;
    rm                      ) shift ; /usr/lib/depot/remove "$@"        ;;
    update                  ) shift ; /usr/lib/depot/update "$@"        ;;
    sign                    ) shift ; /usr/lib/depot/sign "$@"          ;;
    config                  ) shift ; /usr/lib/depot/config "$@"        ;;
    help                    ) echo "$appHelp"                  ; exit 0 ;;
    version|-v|--version    ) echo -e "$appInfo\n\n$copyright" ; exit 0 ;;
    *                       )
        app-info error "Unknown command: \`$1\`. Use '$0 help' to see available commands."
    ;;
esac
